### ISSUE TITLE
Reason behind rescaling of colored MNIST images

### ISSUE THREAD

**Issue by Tom-Lotze** [wouterbulten/deeplearning-resources#1]
Hi Wouter,

I was wondering what the motivation is behind rescaling the colored MNIST images to 64*64 pixels. I wanted to use a comparable dataset with an autoencoder and prototype classification network, but increasing the dimensions from 28 to 64 makes this much slower, so I was curious about the reasons for rescaling. 

Thanks for your time,

**Comment by wouterbulten** [comment]
Hi! Learning larger-sized images is often harder so I do it to make the task more comparable to a real-world scenario. 

For other non-bug typed questions, please see the blog post and (if needed) post a comment there: https://www.wouterbulten.nl/blog/tech/getting-started-with-generative-adversarial-networks/ Thanks :)
